// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using XivMediaPlayer.Server.Models;

#nullable disable

namespace XivMediaPlayer.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260812060000_TvIdleBrandingUrl")]
    partial class TvIdleBrandingUrl
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
#pragma warning restore 612, 618
        }
    }
}
